# config

phonecallsEnabled = true
# date = Now
# expires = 1509070295 [INT]
testMode = false
thisDc = 2
chatSizeMax = 200
megagroupSizeMax = 30000
forwardedCountMax = 100
onlineUpdatePeriodMs = 120000
offlineBlurTimeoutMs = 5000
offlineIdleTimeoutMs = 30000
onlineCloudTimeoutMs = 300000
notifyCloudDelayMs = 30000
notifyDefaultDelayMs = 1500
chatBigSize = 10
pushChatPeriodMs = 60000
pushChatLimit = 2
savedGifsLimit = 200
editTimeLimit = 172800
ratingEDecay = 2419200
stickersRecentLimit = 30
stickersFavedLimit = 5
tmpSessions = 0
pinnedDialogsCountMax = 5
callReceiveTimeoutMs = 20000
callRingTimeoutMs = 90000
callConnectTimeoutMs = 30000
callPacketTimeoutMs = 10000
meUrlPrefix = "https://t.me/"
suggestedLangCode = "en"
langPackVersion = 31

[[DcOptions]]
ipv6 = false
mediaOnly = false
tcpoOnly = false
cdn = false
static = false
id = 2
ipAddress = "127.0.0.1"
port = 12345

[[DisabledFeatures]]
