# biz_server.toml

ver = "0.0.1"
#logPath = "/tmp/frontend.log"
serverId = 1

[server]
name = "session"
protoName = "zproto"
addr = "0.0.0.0:10000"

[discovery]
serviceName = "session"
nodeID = "node1"
rPCAddr = "127.0.0.1:10000"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[authKeyRpcClient]
serviceName = "auth_key"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[bizRpcClient]
serviceName = "biz"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[nbfsRpcClient]
serviceName = "nbfs"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[syncRpcClient]
serviceName = "sync2"
etcdAddrs = ["http://127.0.0.1:2379"]
balancer = "round_robin"

[[redis]]
name = "cache"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
dbNum = "0"
password = ""
