# auth_key.toml

ver = "0.0.1"

[server]
name = "handshake"
protoName = "zproto"
addr = "0.0.0.0:10005"

[discovery]
serviceName = "handshake"
nodeID = "node1"
rPCAddr = "127.0.0.1:10005"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[rpcServer]
addr = "0.0.0.0:10006"

[rpcDiscovery]
serviceName = "auth_key"
nodeID = "node1"
rPCAddr = "127.0.0.1:10006"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[[mysql]]
name = "immaster"
dsn = "root:changeit@/nebulaim?charset=utf8"
#root:1@tcp(127.0.0.1:3306)/nebulaim?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2

[[mysql]]
name = "imslave"
dsn = "root:changeit@/nebulaim?charset=utf8"
# root:1@tcp(127.0.0.1:3306)/nebulaim?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
active = 5
idle = 2
